
name: "Continuous Integration"

on: [push, pull_request]

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.3', '8.0']
        dependency-version: [prefer-lowest, prefer-stable]
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          coverage: none

      - name: Install PHP dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --no-progress --ansi

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit"